#!/usr/bin/env ruby

remember = "install pathogen and backup slime.vim first"

git_bundles = [ 
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/tpope/vim-ragtag.git",
  "git://github.com/tsaleh/vim-align.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/skwp/greplace.vim.git",
  "git://github.com/mattn/gist-vim.git",
  "git://github.com/mattn/zencoding-vim.git",
  "git://github.com/vim-scripts/jQuery.git",
  "git://github.com/vim-scripts/AutoClose.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/scrooloose/nerdcommenter.git",
  "git://github.com/wincent/Command-T.git",
  "git://github.com/mileszs/ack.git",
  "git://github.com/kana/vim-scratch.git",
  "git://github.com/digitaltoad/vim-jade.git",
  "git://github.com/mhz/vim-matchit.git"
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["Yankring", "13554",  "plugin"]
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git submodule add #{url} #{dir}`
  #FileUtils.rm_rf(File.join(dir, ".git"))
end
`git submodule init`

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
